// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1) {
  return window['go']['main']['App']['AddProvider'](arg1);
}

export function DeleteAllHistory() {
  return window['go']['main']['App']['DeleteAllHistory']();
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteHistoryBatch(arg1) {
  return window['go']['main']['App']['DeleteHistoryBatch'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function ExportReport(arg1) {
  return window['go']['main']['App']['ExportReport'](arg1);
}

export function GetAllConfigs() {
  return window['go']['main']['App']['GetAllConfigs']();
}

export function GetHiddenProviderIDs() {
  return window['go']['main']['App']['GetHiddenProviderIDs']();
}

export function GetHistory(arg1, arg2) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2);
}

export function GetProviderDefaults(arg1) {
  return window['go']['main']['App']['GetProviderDefaults'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function ResetAllProviders() {
  return window['go']['main']['App']['ResetAllProviders']();
}

export function RunBatchCheck(arg1) {
  return window['go']['main']['App']['RunBatchCheck'](arg1);
}

export function RunBatchKeyCheck(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RunBatchKeyCheck'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RunCheck(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RunCheck'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveProviderConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveProviderConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetProviderVisibility(arg1, arg2) {
  return window['go']['main']['App']['SetProviderVisibility'](arg1, arg2);
}
