// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {checker} from '../models';
import {store} from '../models';

export function AddProvider(arg1:main.AddProviderReq):Promise<void>;

export function DeleteAllHistory():Promise<void>;

export function DeleteHistory(arg1:number):Promise<void>;

export function DeleteHistoryBatch(arg1:Array<number>):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function ExportReport(arg1:Array<checker.FullCheckResult>):Promise<string>;

export function GetAllConfigs():Promise<Array<store.ProviderConfigRow>>;

export function GetHiddenProviderIDs():Promise<Array<string>>;

export function GetHistory(arg1:number,arg2:number):Promise<main.HistoryListResult>;

export function GetProviderDefaults(arg1:string):Promise<main.ProviderInfo>;

export function GetProviders():Promise<Array<main.ProviderInfo>>;

export function ResetAllProviders():Promise<void>;

export function RunBatchCheck(arg1:Array<main.BatchCheckItem>):Promise<Array<checker.FullCheckResult>>;

export function RunBatchKeyCheck(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<Array<checker.FullCheckResult>>;

export function RunCheck(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<checker.FullCheckResult>;

export function SaveProviderConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetProviderVisibility(arg1:string,arg2:boolean):Promise<void>;
